tags:
  - 個人基本資訊
  - 政黨
  - 家庭背景
  - 連任帶職
  - 政見
  - 學經歷
  - 國防外交
  - 能源環境
  - 性別平權
  - 教育文化
  - 建設交通
  - 經濟財政
  - 社福衛生
  - 司法紀錄
  - 爭議事件
  - 發言表態
  - 其他

politician_groups:
  2024_總統:
    keys: []
    value: ['侯友宜', '趙少康', '賴清德', '蕭美琴', '柯文哲', '吳欣盈']
  2024_立委_不分區_台灣基進:
    keys: []
    value:
      ['史惟筑', '陳奕齊', '黃楓茹', '陳君愷', '楊佩樺', '黃馨瑩', '徐煊博']
  2024_立委_不分區_時代力量:
    keys: []
    value:
      [
        '林依瑩',
        '王寶萱',
        '宋國鼎',
        '江盛',
        '陳泰源',
        '陳昱安',
        '余佳蒨',
        '鄭侑青',
      ]
  2024_立委_不分區_新黨:
    keys: []
    value:
      [
        '王建煊',
        '仉桂美',
        '吳成典',
        '賀樺',
        '林易陞',
        '陳麗玲',
        '戴德滿',
        '王子芩',
      ]
  2024_立委_不分區_親民黨:
    keys: []
    value:
      [
        '李桐豪',
        '陳怡潔',
        '曲兆祥',
        '何偉真',
        '簡泰河',
        '藍志玟',
        '吳建德',
        '黎淑慧',
        '孫信君',
        '黎建南',
      ]
  2024_立委_不分區_中華統一促進黨:
    keys: ['統促黨']
    value: ['丁炳仁', '黃妙如', '肖云霞', '張安樂']
  2024_立委_不分區_臺灣雙語無法黨:
    keys: []
    value: ['陳亭諭', '蕭文乾']
  2024_立委_不分區_中國國民黨:
    keys: []
    value:
      [
        '韓國瑜',
        '柯志恩',
        '葛如鈞',
        '翁曉玲',
        '陳菁徽',
        '吳宗憲',
        '林倩綺',
        '陳永康',
        '許宇甄',
        '謝龍介',
        '蘇清泉',
        '張嘉郡',
        '王育敏',
        '蔡明忠',
        '吳亮儀',
        '李玉蟬',
        '李霞',
        '楊應超',
        '徐弘庭',
        '鍾沛君',
        '江怡臻',
        '簡榮宗',
        '田長沛',
        '沈采穎',
        '林瓊嘉',
        '陳克威',
        '邱一峰',
        '廖怡琇',
        '李縉穎',
        '李茂芊',
        '丁瑀',
        '楊智伃',
        '何嘉霖',
        '康晉瑜',
      ]
  2024_立委_不分區_民主進步黨:
    keys: ['民進黨']
    value:
      [
        '林月琴',
        '沈伯洋',
        '張雅琳',
        '洪申翰',
        '羅美玲',
        '游錫堃',
        '范雲',
        '柯建銘',
        '沈發惠',
        '莊瑞雄',
        '林楚茵',
        '郭昱晴',
        '王正旭',
        '王義川',
        '陳培瑜',
        '陳俊翰',
        '張秀君',
        '黃奕睿',
        '孫一信',
        '吳祥榮',
        '陳慧君 Mulas·Ismahasan',
        '柯富揚',
        '劉柏君',
        '石明謹',
        '曾美玲',
        '黃真瑋',
        '曾湘樺',
        '鄭力嘉',
        '陳右欣',
        '余宛如',
        '許菡芸',
        '周威佑',
        '廖韶吟',
        '蔡宜文',
      ]
  2024_立委_不分區_小民參政歐巴桑聯盟:
    keys: []
    value: ['高芸婷', '林詩涵', '閔柏陵']
  2024_立委_不分區_台灣綠黨:
    keys: []
    value:
      [
        '鍾寶珠',
        '李菁琪',
        '黃柔嘉',
        '吳伊婷',
        '希婻·瑪飛洑',
        '林莉棻',
        '黃慧芬',
        '張竹芩',
      ]
  2024_立委_不分區_台灣維新:
    keys: []
    value: ['蘇煥智', '劉亦恩']
  2024_立委_不分區_司法改革黨:
    keys: []
    value:
      [
        '戴翊如',
        '張靜',
        '李柏融',
        '尤瑞敏',
        '賴伯琦',
        '吳振橐',
        '晏揚清',
        '許韶珍',
        '楊啓珊',
      ]
  2024_立委_不分區_台灣民眾黨:
    keys: []
    value:
      [
        '黃珊珊',
        '黃國昌',
        '陳昭姿',
        '吳春城',
        '麥玉珍',
        '林國成',
        '林憶君',
        '張啓楷',
        '劉書彬',
        '洪毓祥',
        '蔡春綢',
        '王安祥',
        '邱慧洳',
        '陳清龍',
        '李貞秀',
        '許忠信',
        '徐瑞希',
        '楊弘意',
        '陳智菡',
        '莊貽量',
        '林筱淇',
        '蔡豐州',
        '張雪如',
        '湯宏正',
        '林淑芬#1',
        '梁明輝',
        '廖維欣',
        '馮啟彥',
        '林子宇',
        '張清俊',
        '林治華',
        '李家豪',
        '邱于珊',
        '周榆修',
      ]
  2024_立委_不分區_台灣團結聯盟:
    keys: []
    value: ['周倪安', '劉一德', '歐陽瑞蓮', '王思棠', '張登凱', '吳家慶']
  2024_立委_不分區_人民最大黨:
    keys: []
    value: ['林東雄', '賴方靜靜']
  2024_立委_不分區_制度救世島:
    keys: []
    value: ['林麗容', '石人仁', '張怡菁', '古文發', '黃千明']
  2024_立委_臺北市_第1選區:
    value:
      [
        '陳執中',
        '許盛鋒',
        '吳思瑤',
        '張斯綱',
        '張臺勝',
        '胡金城',
        '侯漢廷',
        '賴宗育',
      ]
    keys: ['台北', '北投區', '士林區']
  2024_立委_臺北市_第2選區:
    value: ['游淑慧', '王世堅', '郭啟源', '藍信祺', '何梅娟', '熊嘉玲']
    keys: ['台北', '大同區', '士林區']
  2024_立委_臺北市_第3選區:
    value:
      ['陳源發', '陳一郎', '王鴻薇', '謝佩芬', '余新造', '楊時睿', '高士恩']
    keys: ['台北', '中山區', '松山區']
  2024_立委_臺北市_第4選區:
    value: ['林秋彤', '吳欣岱', '高嘉瑜', '李彥秀', '黃啟彬']
    keys: ['台北', '內湖區', '南港區']
  2024_立委_臺北市_第5選區:
    value:
      [
        '于美人',
        '吳沛憶',
        '林志成',
        '張華特',
        '李慧曦',
        '蘇諍',
        '鍾小平',
        '許敬民',
        '陳燕玉',
        '孫智麗',
      ]
    keys: ['台北', '萬華區', '中正區']
  2024_立委_臺北市_第6選區:
    value: ['羅智強', '崔建章', '苗博雅', '朱翊銘', '張雪卿']
    keys: ['台北', '大安區']
  2024_立委_臺北市_第7選區:
    value: ['徐巧芯', '李承龍', '許淑華', '陳韋安', '羅丹']
    keys: ['台北', '信義區', '松山區']
  2024_立委_臺北市_第8選區:
    value:
      [
        '王閔生',
        '夏萬浪',
        '胡之壯',
        '賴宣任',
        '張其祿',
        '劉佩玲',
        '賴士葆',
        '張維學',
      ]
    keys: ['台北', '文山區', '中正區']
  2024_立委_新北市_第1選區:
    value: ['洪孟楷', '翁藤原', '何博文', '徐百弟', '游清池']
    keys: ['石門區', '三芝區', '淡水區', '八里區', '林口區', '泰山區']
  2024_立委_新北市_第2選區:
    value: ['李有宜', '林淑芬#2', '何淯笙']
    keys: ['五股區', '蘆洲區', '三重區']
  2024_立委_新北市_第3選區:
    value: ['李坤城', '陳東雲', '蔡明堂', '蘇卿彥']
    keys: ['三重區']
  2024_立委_新北市_第4選區:
    value: ['吳秉叡', '蔣欣璋', '蘇輝湟', '邱吉均', '洪懿馥']
    keys: ['新莊區']
  2024_立委_新北市_第5選區:
    value: ['蘇巧慧', '洪佳君']
    keys: ['樹林區', '鶯歌區', '新莊區']
  2024_立委_新北市_第6選區:
    value: ['張宏陸', '黃淑珍', '林國春']
    keys: ['板橋區']
  2024_立委_新北市_第7選區:
    value: ['羅致政', '葉元之', '劉書婷']
    keys: ['板橋區']
  2024_立委_新北市_第8選區:
    value: ['張智倫', '吳崢', '邱臣遠']
    keys: ['中和區']
  2024_立委_新北市_第9選區:
    value: ['林德福', '莊銘淵', '陳愷寧']
    keys: ['永和區', '中和區']
  2024_立委_新北市_第10選區:
    value: ['袁興', '吳琪銘', '林金結', '孟藹倫']
    keys: ['土城區', '三峽區']
  2024_立委_新北市_第11選區:
    value: ['曾柏瑜', '陳聖', '羅明才', '鄭添泉', '張家榛', '魏趨安']
    keys: ['新店區', '深坑區', '石碇區', '坪林區', '烏來區']
  2024_立委_新北市_第12選區:
    value: ['李佳蒨', '賴品妤', '黃瑞傳', '廖先翔', '陳長志', '楊木火']
    keys: ['汐止區', '金山區', '萬里區', '瑞芳區', '平溪區', '雙溪區', '貢寮區']
  2024_立委_桃園市_第1選區:
    value: ['鄭運鵬', '牛煦庭', '馬治薇']
    keys: ['蘆竹區', '龜山區', '桃園區']
  2024_立委_桃園市_第2選區:
    value: ['黃世杰', '涂權吉', '陳志豪', '王思玟']
    keys: ['楊梅區', '新屋區', '觀音區', '大園區']
  2024_立委_桃園市_第3選區:
    value: ['游智彬', '彭俊豪', '徐鶯慈', '魯明哲', '戴浙']
    keys: ['中壢區']
  2024_立委_桃園市_第4選區:
    value: ['萬美玲', '范綱祥', '甘乃迪', '黃明莉']
    keys: ['桃園區']
  2024_立委_桃園市_第5選區:
    value: ['劉仁照', '賴香伶', '呂玉玲', '易乃文']
    keys: ['平鎮區', '龍潭區']
  2024_立委_桃園市_第6選區:
    value: ['葉堂宇', '趙正宇', '邱若華', '劉睿宸', '翁紹庭', '李慕妍']
    keys: ['八德區', '大溪區', '復興區', '中壢區']
  2024_立委_臺中市_第1選區:
    value: ['蔡壁如', '蔡其昌', '賴信全', '劉燈鐘']
    keys: ['台中', '大甲區', '大安區', '外埔區', '清水區', '梧棲區']
  2024_立委_臺中市_第2選區:
    value: ['顏寬恒', '林靜儀', '紀銘修', '洪麗華']
    keys: ['台中', '沙鹿區', '龍井區', '大肚區', '烏日區', '霧峰區']
  2024_立委_臺中市_第3選區:
    value: ['謝子涵', '楊瓊瓔', '張烱春']
    keys: ['台中', '后里區', '神岡區', '大雅區', '潭子區']
  2024_立委_臺中市_第4選區:
    value: ['廖偉翔', '張廖萬堅', '李海碩', '林中翊', '陳志彬']
    keys: ['台中', '西屯區', '南屯區']
  2024_立委_臺中市_第5選區:
    value:
      [
        '莊競程',
        '苗豐隆',
        '黃健豪',
        '謝旻汎',
        '彭振芳',
        '蔡善雯',
        '林澤培',
        '陳維新',
      ]
    keys: ['台中', '北屯區', '北區']
  2024_立委_臺中市_第6選區:
    value: ['羅廷瑋', '賀姿華', '紀文清', '江肇國', '黃千庭']
    keys: ['台中', '東區', '南區', '中區', '西區']
  2024_立委_臺中市_第7選區:
    value: ['林家興', '何欣純', '林振東']
    keys: ['台中', '太平區', '大里區']
  2024_立委_臺中市_第8選區:
    value: ['謝志忠', '江啟臣']
    keys: ['台中', '豐原區', '石岡區', '東勢區', '新社區', '和平區']
  2024_立委_臺南市_第1選區:
    value: ['侯陸太', '魏耀乾', '賴惠員', '周宏昌', '林芳竹', '蔡承攸']
    keys:
      [
        '台南',
        '後壁區',
        '白河區',
        '北門區',
        '學甲區',
        '鹽水區',
        '新營區',
        '柳營區',
        '東山區',
        '將軍區',
        '下營區',
        '六甲區',
      ]
  2024_立委_臺南市_第2選區:
    value: ['陳昆和', '郭國文', '詹秋嫻']
    keys:
      [
        '台南',
        '七股區',
        '佳里區',
        '麻豆區',
        '官田區',
        '善化區',
        '大內區',
        '玉井區',
        '楠西區',
        '西港區',
        '安定區',
        '山上區',
        '左鎮區',
        '南化區',
      ]
  2024_立委_臺南市_第3選區:
    value: ['陳亭妃', '姚正玉']
    keys: ['台南', '安南區', '北區']
  2024_立委_臺南市_第4選區:
    value: ['林宜瑾', '劉清田', '李全教']
    keys: ['台南', '新市區', '永康區', '新化區']
  2024_立委_臺南市_第5選區:
    value: ['林俊憲', '王家貞', '蕭燐洪']
    keys: ['台南', '安平區', '中西區', '南區', '東區']
  2024_立委_臺南市_第6選區:
    value: ['陳永和', '王定宇', '陳以信']
    keys: ['台南', '仁德區', '歸仁區', '關廟區', '龍崎區', '東區']
  2024_立委_高雄市_第1選區:
    value: ['邱議瑩', '曾尹儷', '劉承智', '林義迪']
    keys:
      [
        '桃源區',
        '那瑪夏區',
        '甲仙區',
        '六龜區',
        '杉林區',
        '內門區',
        '旗山區',
        '美濃區',
        '茂林區',
        '阿蓮區',
        '田寮區',
        '燕巢區',
        '大樹區',
        '大社區',
      ]
  2024_立委_高雄市_第2選區:
    value: ['邱志偉', '曹桓榮']
    keys:
      [
        '茄萣區',
        '湖內區',
        '路竹區',
        '永安區',
        '岡山區',
        '彌陀區',
        '梓官區',
        '橋頭區',
      ]
  2024_立委_高雄市_第3選區:
    value: ['張正達', '李柏毅', '李眉蓁', '郭璽', '陳銓霖']
    keys: ['楠梓區', '左營區']
  2024_立委_高雄市_第4選區:
    value: ['林岱樺', '陳若翠']
    keys: ['仁武區', '鳥松區', '大寮區', '林園區']
  2024_立委_高雄市_第5選區:
    value: ['黃柏霖', '李昆澤', '楊椒喬', '張芳愉']
    keys: ['三民區', '苓雅區']
  2024_立委_高雄市_第6選區:
    value: ['黃捷', '郭倍宏', '陳美雅']
    keys: ['鼓山區', '鹽埕區', '前金區', '新興區', '苓雅區']
  2024_立委_高雄市_第7選區:
    value: ['王和平統一', '朱磊', '鍾易仲', '許智傑', '洪啟修']
    keys: ['鳳山區']
  2024_立委_高雄市_第8選區:
    value: ['湛秀英', '賴瑞隆', '李政憲', '李明璇']
    keys: ['旗津區', '前鎮區', '小港區']
  2024_立委_新竹縣_第1選區:
    value: ['詹紀緹', '徐欣瑩', '余筱菁', '劉台穠', '劉復嵐']
    keys: ['新豐鄉', '湖口鄉', '新埔鎮', '芎林鄉', '關西鎮', '尖石鄉', '竹北市']
  2024_立委_新竹縣_第2選區:
    value: ['曾聖凱', '林思銘', '王婉諭', '黃秀龍']
    keys: ['竹東鎮', '寶山鄉', '北埔鄉', '峨眉鄉', '橫山鄉', '五峰鄉', '竹北市']
  2024_立委_苗栗縣_第1選區:
    value: ['陳超明', '康世明']
    keys:
      [
        '竹南鎮',
        '後龍鎮',
        '造橋鄉',
        '通霄鎮',
        '西湖鄉',
        '銅鑼鄉',
        '三義鄉',
        '苑裡鎮',
      ]
  2024_立委_苗栗縣_第2選區:
    value: ['曾玟學', '邱鎮軍']
    keys:
      [
        '頭份市',
        '三灣鄉',
        '南莊鄉',
        '苗栗市',
        '公館鄉',
        '頭屋鄉',
        '大湖鄉',
        '獅潭鄉',
        '卓蘭鎮',
        '泰安鄉',
      ]
  2024_立委_彰化縣_第1選區:
    value: ['陳秀寳', '蘇群傑', '阮厚爵']
    keys: ['伸港鄉', '線西鄉', '和美鎮', '鹿港鎮', '福興鄉', '秀水鄉']
  2024_立委_彰化縣_第2選區":
    value: ['黃秀芳', '楊曜聰']
    keys: ['彰化市', '花壇鄉', '芬園鄉']
  2024_立委_彰化縣_第3選區:
    value: ['洪建興', '吳音寧', '桂麗娜', '謝衣鳯']
    keys:
      [
        '芳苑鄉',
        '二林鎮',
        '埔鹽鄉',
        '溪湖鎮',
        '埔心鄉',
        '大城鄉',
        '竹塘鄉',
        '埤頭鄉',
        '北斗鎮',
        '溪州鄉',
      ]
  2024_立委_彰化縣_第4選區:
    value: ['陳素月', '鄭錫懋', '蔡念諶', '鄭俊雄']
    keys: ['大村鄉', '員林市', '永靖鄉', '社頭鄉', '田尾鄉', '田中鎮', '二水鄉']
  2024_立委_南投縣_第1選區:
    value: ['蔡銘軒', '許文忠', '林金潭', '馬文君', '李圓恩']
    keys: ['埔里鎮', '草屯鎮', '中寮鄉', '魚池鄉', '國姓鄉', '仁愛鄉']
  2024_立委_南投縣_第2選區:
    value: ['游顥', '陳癸佑', '蔡培慧']
    keys: ['南投市', '名間鄉', '集集鎮', '竹山鎮', '鹿谷鄉', '水里鄉', '信義鄉']
  2024_立委_雲林縣_第1選區:
    value: ['李昭儀', '丁學忠', '蘇治芬', '吳炳輝', '郭炳宏', '陳俊龍']
    keys:
      [
        '麥寮鄉',
        '臺西鄉',
        '東勢鄉',
        '褒忠鄉',
        '土庫鎮',
        '虎尾鎮',
        '四湖鄉',
        '元長鄉',
        '口湖鄉',
        '水林鄉',
        '北港鎮',
      ]
  2024_立委_雲林縣_第2選區:
    value: ['邱良閱', '劉建國']
    keys:
      [
        '崙背鄉',
        '二崙鄉',
        '西螺鎮',
        '莿桐鄉',
        '林內鄉',
        '斗六市',
        '大埤鄉',
        '斗南鎮',
        '古坑鄉',
      ]
  2024_立委_嘉義縣_第1選區:
    value: ['蔡易餘', '詹琬蓁']
    keys:
      [
        '六腳鄉',
        '東石鄉',
        '朴子市',
        '太保市',
        '布袋鎮',
        '義竹鄉',
        '鹿草鄉',
        '水上鄉',
      ]
  2024_立委_嘉義縣_第2選區:
    value: ['陳冠廷', '林國慶', '黃一哲', '廖昱婧', '簡銘傑']
    keys:
      [
        '溪口鄉',
        '大林鎮',
        '梅山鄉',
        '新港鄉',
        '民雄鄉',
        '竹崎鄉',
        '中埔鄉',
        '番路鄉',
        '阿里山鄉',
        '大埔鄉',
      ]
  2024_立委_屏東縣_第1選區:
    value:
      ['蔣月惠', '鍾佳濱', '黃明賢', '李孟翰', '張庭源', '鄭清原', '曾鈺庭']
    keys:
      [
        '里港鄉',
        '高樹鄉',
        '三地門鄉',
        '霧臺鄉',
        '九如鄉',
        '鹽埔鄉',
        '長治鄉',
        '內埔鄉',
        '瑪家鄉',
        '屏東市',
        '麟洛鄉',
      ]
  2024_立委_屏東縣_第2選區:
    value: ['蘇孟淳', '吳媚宮', '徐富癸', '何秋葺']
    keys:
      [
        '萬丹鄉',
        '泰武鄉',
        '竹田鄉',
        '萬巒鄉',
        '潮州鎮',
        '新園鄉',
        '崁頂鄉',
        '南州鄉',
        '新埤鄉',
        '來義鄉',
        '東港鎮',
        '林邊鄉',
        '佳冬鄉',
        '枋寮鄉',
        '春日鄉',
        '枋山鄉',
        '獅子鄉',
        '牡丹鄉',
        '車城鄉',
        '滿州鄉',
        '恆春鎮',
        '琉球鄉',
      ]
  2024_立委_宜蘭縣:
    value: ['陳俊宇', '黃琤婷', '陳琬惠', '林錦坤', '邱介勲', '林意評']
    keys: ['宜蘭縣']
  2024_立委_花蓮縣:
    value: ['許願神', '張美慧', '傅崐萁', '周玉梅']
    keys: ['花蓮縣']
  2024_立委_臺東縣:
    value: ['賴坤成', '黃婉茹', '黃建賓', '許瑞貴', '劉櫂豪', '陳長宏']
    keys: ['台東', '臺東縣']
  2024_立委_澎湖縣:
    value: ['陳慧娟', '吳政杰', '楊曜']
    keys: ['澎湖縣']
  2024_立委_金門縣:
    value: ['陳玉珍', '尚文凱', '洪和成', '歐陽儀雄']
    keys: ['金門縣']
  2024_立委_連江縣:
    value: ['李問', '陳雪生', '曹爾凱']
    keys: ['連江縣']
  2024_立委_基隆市:
    value: ['鄭文婷', '黃傑陽', '邱紹祐', '王醒之', '謝海菁', '林沛祥']
    keys: ['基隆市']
  2024_立委_新竹市:
    value:
      ['柯美蘭', '鄭正鈐', '林志潔', '邱顯智', '趙福龍', '楊清華', '王榮德']
    keys: ['新竹市']
  2024_立委_嘉義市:
    value: ['張秀華', '陳玥妗', '簡明廉', '林智勲', '王美惠', '蔡松益']
    keys: ['嘉義市']
  2024_立委_山地原住民:
    value:
      [
        '高金素梅',
        '孔文吉',
        'Savungaz Valincinan',
        '高畹芯',
        '林果',
        '林世偉',
        '張子孝',
        '伍麗華 Saidhai．Tahovecahe',
        '盧縣一',
        '胡黃廣文',
      ]
    keys: []
  2024_立委_平地原住民:
    value:
      [
        '陳政宗',
        '陳瑩',
        '陳國榮',
        '米甘幹．理佛克',
        '忠仁．達祿斯',
        '吳建智咖啡哥',
        '黃仁',
        '洪曹純明',
        '鄭天財 Sra‧Kacaw',
        '高美珠',
      ]
    keys: []
